--This is to create the different tables------------------------------------

CREATE TYPE FLAG AS ENUM('Y', 'N');

CREATE TABLE FACT_TABLE(
TRIP_ID int PRIMARY KEY,
VENDORID int, 
DATE_TIME_ID int, 
PASSENGER_COUNT_ID int, 
TRIP_DISTANCE_ID int, 
RATECODE_ID int, 
STORE_AND_FWD_FLAG FLAG,
PICKUP_LOC_ID int, 
DROPOFF_LOC_ID int, 
PAYMENT_TYPE_ID int, 
FARE_AMOUNT_ID int)

CREATE TABLE DROPOFF_LOC(
DROPOFF_LOC_ID int PRIMARY KEY,
DROPOFF_LONGITUDE float, 
DROPOFF_LATITUDE float);

CREATE TABLE PICKUP_LOC(
PICKUP_LOC_ID int PRIMARY KEY,
PICKUP_LONGITUDE float, 
PICKUP_LATITUDE float);

CREATE TABLE RATECODE_TABLE(
RATECODE_ID int PRIMARY KEY,
RATECODEID int, 
RATECODE_NAME VARCHAR(50));

CREATE TABLE TRIP_DISTANCE_TABLE(
TRIP_DISTANCE_ID int PRIMARY KEY,
TRIP_DISTANCE float);

CREATE TABLE PAYMENT_TYPE_TABLE(PAYMENT_TYPE_ID int PRIMARY KEY, 
PAYMENT_TYPE int, 
PAYMENT_TYPE_NAME VARCHAR(50));


CREATE TABLE PASSENGER_COUNT_TABLE(
PASSENGER_COUNT_ID int PRIMARY KEY,
PASSENGER_COUNT int);

CREATE TABLE FARE_AMOUNT_TABLE(
FARE_AMOUNT_ID int PRIMARY KEY,
FARE_AMOUNT float, 
EXTRA float, 
MTA_TAX float, 
TIP_AMOUNT float, 
TOLLS_AMOUNT float, 
IMPROVEMENT_SURCHARGE float, 
TOTAL_AMOUNT float);


CREATE TABLE DATE_TIME_TABLE(
DATE_TIME_ID int PRIMARY KEY,
TPEP_PICKUP_DATE_TIME timestamp, 
PICKUP_TIME TIME,
PICKUP_DATE date, 
PICKUP_DAY int, 
TPEP_DROPOFF_DATE_TIME timestamp, 
DROPOFF_TIME TIME,
DROPOFF_DATE date, 
DROPOFF_DAY int);
-------------------------------------------------------------------------------


-- Find the average tip by payment_type

SELECT PT.PAYMENT_TYPE_NAME,
	AVG(FA.TIP_AMOUNT) AS AVG_TIP
FROM PAYMENT_TYPE_TABLE PT
LEFT JOIN FARE_AMOUNT_TABLE FA ON PT.PAYMENT_TYPE_ID = FA.FARE_AMOUNT_ID
GROUP BY 1;

-- Total number of Trips by passenger count

SELECT PCT.PASSENGER_COUNT,
	COUNT(FT.TRIP_ID)
FROM FACT_TABLE FT
LEFT JOIN PASSENGER_COUNT_TABLE PCT ON FT.TRIP_ID = PCT.PASSENGER_COUNT_ID
GROUP BY 1;

--Joining all Tables---------------------------------------------------------
Create or replace table uber_analysis as (
SELECT *
FROM FACT_TABLE FT
JOIN DATE_TIME_TABLE DTT ON DTT.DATE_TIME_ID = FT.DATE_TIME_ID
JOIN DROPOFF_LOC DL ON DL.DROPOFF_LOC_ID = FT.DROPOFF_LOC_ID
JOIN FARE_AMOUNT_TABLE FA ON FA.FARE_AMOUNT_ID = FT.FARE_AMOUNT_ID
JOIN PASSENGER_COUNT_TABLE PCT ON PCT.PASSENGER_COUNT_ID = FT.PASSENGER_COUNT_ID
JOIN PAYMENT_TYPE_TABLE PTT ON PTT.PAYMENT_TYPE_ID = FT.PAYMENT_TYPE_ID
JOIN PICKUP_LOC PL ON PL.PICKUP_LOC_ID = PL.PICKUP_LOC_ID
JOIN RATECODE_TABLE RT ON RT.RATECODE_ID = FT.RATECODE_ID
JOIN TRIP_DISTANCE_TABLE TDL ON TDL.TRIP_DISTANCE_ID = FT.TRIP_DISTANCE_ID);
------------------------------------------------------------------------------